apiVersion: v2
name: sdk-scheme-adapter-svc
version: 1.3.0
description: A Helm chart for Kubernetes
appVersion: "v23.0.1"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/sdk-scheme-adapter
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
dependencies:
  - name: common
    repository: "https://mojaloop.github.io/charts/repo"
    tags:
      - moja-common
    version: 2.1.0
