apiVersion: v2
description: Simulator Helm Chart for Simulators
name: simulator
version: 13.0.1
appVersion: "12.0.0"
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
  - name: Tom Daly
    email: tomd@crosslaketech.com
dependencies:
  - name: common
    repository: "https://mojaloop.github.io/charts/repo"
    version: 2.1.0
    tags:
      - moja-common
