apiVersion: v2
description: Mojaloop Bulk Helm chart for Kubernetes
name: mojaloop-bulk
version: 15.1.0
appVersion: "bulk-api-adapter: v15.0.3; central-ledger: v17.0.3"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
  - name: Tom Daly
    email: tomd@crosslaketech.com
dependencies:
  - name: bulk-api-adapter
    version: 13.0.0
    repository: "file://../bulk-api-adapter"
    condition: bulk-api-adapter.enabled
  - name: bulk-centralledger
    version: 14.0.0
    repository: "file://../bulk-centralledger"
    condition: bulk-centralledger.enabled
  - name: common
    repository: https://mojaloop.github.io/charts/repo
    version: 2.1.0
    tags:
        - moja-common
