apiVersion: v2
version: 14.3.0
appVersion: "14.1.0"
description: A Helm chart for Kubernetes
name: account-lookup-service
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
  - name: Tom Daly
    email: tomd@crosslaketech.com
dependencies:
  - name: common
    repository: "https://mojaloop.github.io/charts/repo"
    version: 2.1.0
    tags:
      - moja-common
