name: account-lookup-service

sources:
  account-lookup-service:
    kind: githubrelease
    spec:
      owner: mojaloop
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      repository: account-lookup-service
  als-oracle-pathfinder:
    kind: githubrelease
    spec:
      owner: mojaloop
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      repository: als-oracle-pathfinder
  event-sidecar:
    kind: githubrelease
    spec:
      owner: mojaloop
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      repository: event-sidecar
  
conditions:
  docker-account-lookup-service:
    sourceid: account-lookup-service
    kind: dockerimage
    spec:
      image: mojaloop/account-lookup-service
  docker-als-oracle-pathfinder:
    sourceid: als-oracle-pathfinder
    kind: dockerimage
    spec:
      image: mojaloop/als-oracle-pathfinder
  docker-event-sidecar:
    sourceid: event-sidecar
    kind: dockerimage
    spec:
      image: mojaloop/event-sidecar

targets:
  account-lookup-service:
    sourceid: account-lookup-service
    kind: helmchart
    spec:
      name: account-lookup-service
      file: values.yaml
      key: $.account-lookup-service.image.tag
  account-lookup-service-admin:
    sourceid: account-lookup-service
    kind: helmchart
    spec:
      name: account-lookup-service
      file: values.yaml
      key: $.account-lookup-service-admin.image.tag
  als-oracle-pathfinder:
    sourceid: als-oracle-pathfinder
    kind: helmchart
    spec:
      name: account-lookup-service
      file: values.yaml
      key: $.als-oracle-pathfinder.image.tag
  chart_admin__account-lookup-service:
    sourceid: account-lookup-service
    kind: helmchart
    spec:
      name: account-lookup-service/chart-admin
      file: values.yaml
      key: $.image.tag
      appversion: true
  chart_admin__event-sidecar:
    sourceid: event-sidecar
    kind: helmchart
    spec:
      name: account-lookup-service/chart-admin
      file: values.yaml
      key: $.sidecar.image.tag
  chart_service__account-lookup-service:
    sourceid: account-lookup-service
    kind: helmchart
    spec:
      name: account-lookup-service/chart-service
      file: values.yaml
      key: $.image.tag
      appversion: true
  chart_service__event-sidecar:
    sourceid: event-sidecar
    kind: helmchart
    spec:
      name: account-lookup-service/chart-service
      file: values.yaml
      key: $.sidecar.image.tag