name: bulk-api-adapter

sources:
  bulk-api-adapter:
    kind: githubrelease
    spec:
      owner: mojaloop
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      repository: bulk-api-adapter
  
conditions:
  docker-bulk-api-adapter:
    sourceid: bulk-api-adapter
    kind: dockerimage
    spec:
      image: mojaloop/bulk-api-adapter

targets:
  bulk-api-adapter-service:
    sourceid: bulk-api-adapter
    kind: helmchart
    spec:
      name: bulk-api-adapter
      file: values.yaml
      key: $.bulk-api-adapter-service.image.tag
  bulk-api-adapter-handler-notification:
    sourceid: bulk-api-adapter
    kind: yaml
    spec:
      file: bulk-api-adapter/values.yaml
      key: $.bulk-api-adapter-handler-notification.image.tag
  chart-adapter-notification__bulk-api-adapter:
    sourceid: bulk-api-adapter
    kind: helmchart
    spec:
      name: bulk-api-adapter/chart-handler-notification
      file: values.yaml
      key: $.image.tag
  chart-service__bulk-api-adapter:
    sourceid: bulk-api-adapter
    kind: helmchart
    spec:
      name: bulk-api-adapter/chart-service
      file: values.yaml
      key: $.image.tag