apiVersion: v2
name: efk
description: A Helm chart containing ELK for Kubernetes
version: 12.6.0
appVersion: "elasticsearch: 7.11.1; kibana: 7.11.1; apm-server: 7.11.1; fluentd-elasticsearch: 3.2.0"
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
  - name: Tom Daly
    email: tomd@crosslaketech.com
dependencies:
  - name: fluentd-elasticsearch
    version: 13.11.0
    repository: "https://kokuwaio.github.io/helm-charts"
    condition: fluentd-elasticsearch.enabled
  - name: elasticsearch
    version: 8.5.1
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
  - name: kibana
    version: 8.5.1
    repository: "https://helm.elastic.co"
    condition: kibana.enabled
  - name: apm-server
    version: 8.5.1
    repository: "https://helm.elastic.co"
    condition: apm-server.enabled
  - name: common
    repository: https://mojaloop.github.io/charts/repo
    version: 2.1.0
    tags:
      - moja-common
