apiVersion: v2
description: Forensic Logging Sidecar Helm chart for Kubernetes
name: forensicloggingsidecar
version: 2.7.0
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/forensic-logging-sidecar
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
  - name: Tom Daly
    email: tomd@crosslaketech.com
dependencies:
  - name: centralkms
    version: 2.5.0
    repository: "file://../centralkms"
    condition: centralkms.enabled
  - name: postgresql
    version: 8.6.4
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
  - name: common
    repository: https://mojaloop.github.io/charts/repo
    version: 2.1.0
    tags:
      - moja-common
