apiVersion: v2
description: Example Helm chart for mojaloop backend dependencies
name: example-mojaloop-backend
version: 15.7.0
appVersion: "nginx: 4.4.2; mysql: 9.18.0; kafka: 26.8.0; mongodb: 14.7.0; redis: 18.8.0"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
  - name: Vijay Kumar Guthi
    email: vijaya.guthi@modusbox.com
  - name: Tom Daly
    email: tomd@crosslaketech.com
dependencies:
  - name: kafka
    alias: kafka
    condition: kafka.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - mojaloop
      - dependency
      - backend
      - kafka
    version: 26.8.0
  ## mysql database
  - name: mysql
    alias: mysql
    condition: mysql.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - mojaloop
      - dependency
      - backend
      - mysql
      - centralledger
      - account-lookup
    version: 9.18.0
  ## Bulk backend
  - name: mongodb
    alias: cl-mongodb
    condition: cl-mongodb.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - mojaloop
      - dependency
      - backend
      - mongodb
      - centralledger
    version: 14.7.0
  ## Central-event-processor backend
  - name: mongodb
    alias: cep-mongodb
    condition: cep-mongodb.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - mojaloop
      - dependency
      - backend
      - mongodb
      - centralledger
    version: 14.7.0
  - name: mongodb
    alias: ttk-mongodb
    condition: ttk-mongodb.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - mojaloop
      - dependency
      - backend
      - mongodb
      - centralledger
    version: 14.7.0
  ## Redis for SDK-Scheme-Adapter that are part of the TTKSims
  - name: redis
    alias: ttksims-redis
    condition: ttksims-redis.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - mojaloop
      - dependency
      - backend
      - redis
      - sdk
      - bulk
      - ttksims
    version: 18.8.0
  ## Redis for Thirdparty Auth-Service
  - name: redis
    alias: auth-svc-redis
    condition: auth-svc-redis.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - mojaloop
      - dependency
      - backend
      - redis
      - thirdparty
    version: 18.8.0
